# Generated by Django 6.0.1 on 2026-04-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
