# Generated by Django 6.0.2 on 2026-04-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0003_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.AddField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="careerportal.employee",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(default="2026-12-31"),
        ),
    ]
