# Generated by Django 6.0.1 on 2026-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0005_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="required_degree",
            field=models.CharField(
                choices=[
                    ("high_school", "High School Diploma"),
                    ("bachelors", "Bachelor's Degree"),
                    ("masters", "Master's Degree"),
                    ("phD", "PhD"),
                    ("post_doc", "Post-Doctorate"),
                ],
                default="bachelors",
                max_length=50,
            ),
        ),
    ]
