# Generated by Django 6.0.2 on 2026-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0006_job_required_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("internship", "Internship"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pay_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="paid",
                max_length=10,
            ),
        ),
    ]
