# Generated by Django 6.0.2 on 2026-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0007_job_job_type_job_pay_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contact_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Include contact email, phone, and/or company website link.",
            ),
        ),
    ]
