# Generated by Django 6.0.1 on 2026-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0010_application_status_alter_job_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("reviewing", "Reviewing"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="reviewing",
                max_length=20,
            ),
        ),
    ]
