# Generated by Django 6.0.1 on 2026-06-01 17:43

import careerportal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0011_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cvs/",
                validators=[careerportal.validators.validate_pdf],
            ),
        ),
    ]
