# Generated by Django 6.0.2 on 2026-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerportal", "0012_alter_application_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In Person"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                max_length=20,
            ),
        ),
    ]
